// This file is auto-generated by Payload CMS.
// Run `pnpm --filter=cms generate:types` to regenerate.
// Do NOT edit manually.

export interface Config {
  collections: {
    users: User
    media: Media
  }
  globals: Record<string, never>
}

export interface User {
  id: string
  email: string
  createdAt: string
  updatedAt: string
}

export interface Media {
  id: string
  alt: string
  url?: string
  filename?: string
  mimeType?: string
  filesize?: number
  width?: number
  height?: number
  createdAt: string
  updatedAt: string
}
